### PR TITLE
Publish tgui logs

### PR DESCRIPTION
**Pull request by stylemistake**
Will be a useful addition for collecting tgui-related errors and statistics. Hopefully I have added it at the right spot.

### CODE REVIEW

**Comment by stylemistake** [comment]
bump.

**Comment by stylemistake** [comment]
Ok fuck this.

**Comment by MrStonedOne** [comment]
Sorry for the delay.

So the primary thing I don't like about this is that it has unnecessary writes (writing to a temp file that then has to be re-read and re-written by gzip is a waste), and it loads the entire file into memory rather then read line by line.

The correct workflow for processing files should be

1. Read line
1. Process line
1. Write line compressed to file in the target directory.

the parse runtime function provides a great example of this. 

If you can't get to this i'll try to find time to do this myself the weekend after next.

**Comment by stylemistake** [comment]
I closed this for a different reason though. Tgui logs are only useful for debugging, and I pull requested this as a way to gain access over these logs before I was a maintainer, and realistically, only devs are going to look through them. They have very little statistical value.

**Pull request closed without merging**
