### PR TITLE
Remove /vg/station link.

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by praisenarsie** [comment]
Reasoning?

**Comment by DoctoreMad** [comment]
SEKRIT CLUUUUUB

**Comment by gbasood** [comment]
Because we asked

**Comment by N3X15** [comment]
Explains all the shitters we've been getting recently.

stewy eats gun

**Comment by gbasood** [comment]
Unrelated, but why even link to 8ch vg?

**Comment by praisenarsie** [comment]
"recently" you make me laugh.

**Comment by PJB3005** [comment]
Just merge it, please.

**Comment by praisenarsie** [comment]
It's such an obscure and ignored button on the website though.

**Comment by clusterfack** [comment]
In that case it didn't serve any purpose in the first place

**Comment by DoctoreMad** [comment]
Did you know that this PR got splayed on both TGstation servers the moment you made it because of the bot?
Good job.

**Comment by MrStonedOne** [comment]
Ya, all prs are announced to both servers.

Also, my suggestion would be to drop the subject before I start creating big bold links on every page saying to not go to /vg/

**Comment by clusterfack** [comment]
I mean, merging the PR would essentially resolve the issue for everyone so?

**Comment by DoctoreMad** [comment]
By the way, when you close it it'll be announced again so you better speed close it unless you want to be closed a hour later(where the 50+ playerbase will see it), I'd recommend you close it now.

**Comment by ShiftyRail** [comment]
PJB, of all people, making this PR

**Comment by gbasood** [comment]
>Also, my suggestion would be to drop the subject before I start creating big bold links on every page saying to not go to /vg/

How's this a threat exactly?
Either people follow the link because you told them not to, or they don't because you told them not to

**Comment by gbasood** [comment]
Honestly hilarious that this got so confrontational so quickly, actually. It's like you want to pretend to be associated with us badly enough to get into a semantics argument over it.

**Comment by Shadowmech88** [comment]
/vg/station prefers a slower, more manageable influx of players than what a standard SS13 server receives. Part of the way this is maintained is the culling of external links to the server, reducing the number of people who happen to discover it.
It would be appreciated by everyone on our server if the link to our server's website was removed.

**Comment by DoctoreMad** [comment]
Well folks, don't say I didn't warn you.

**Comment by praisenarsie** [comment]
> It's such an obscure and ignored button on the website though.

You literally made it more popular by announce it on both servers and the #coderbus irc. Plus you already have a slow and manageable playerbase. Plus, you already have a public github, website, etc. So, just stop okay? It doesn't matter?

**Comment by gbasood** [comment]
It apparently matters to *you* guys though. We just want it removed. Why's it such a big deal?
@DoctoreMad oh boy this sure will accomplish something huh

**Comment by clusterfack** [comment]
We are not the ones doing anything, it is your own link on your website and your own bot. We are merely asking you to cease, I don't see why this is an issue.

**Comment by Shadowmech88** [comment]
We have a slow and manageable playerbase because we make an effort to remove external links to our server, as is being done now.

**Comment by PJB3005** [comment]
@praisenarsie if it doesn't matter whether or not we have the button then the damage from the announcement is already done and you're actively making it worse by making such a big deal out of it.

Also I feel like the result justifies the means here.

**Comment by N3X15** [comment]
Here's the bottom line.

* Your developers, especially MSO, have known our policies about public links to our server.
* We have repeatedly asked you not to link to our server.
* You did it anyway.
* We asked you via this PR to take it down.

And here we are.

**Comment by DeadminGoldsteelForKillingPomf** [comment]
just quick merge this, nobody has an argument against it

**Comment by PJB3005** [comment]
@N3X15 by the way I checked archive.is, this link's been here since 2015. It's not recent and I do believe mso's claim of not being web host when it was added.

It still doesn't justify the refusal to remove it though.

**Comment by DoctoreMad** [comment]
Would you look at that someone just got ghosted when he just made a post 6 minutes ago
The end times are near folks

**Comment by MrStonedOne** [comment]
That is odd actually. I bet it was an autobanned sock puppet account.

**Comment by ShiftyRail** [comment]
Thinking of it, there is no real reason to refuse this request. If by chance you _really_ like our server, you would understand why we ask this.

**Comment by DoctoreMad** [comment]
>there is no real reason to refuse this request

CAVING IN TO TERRORIST REQUESTS

**Comment by clusterfack** [comment]
@DoctoreMad You shouldn't even be on this website considering you were banned for posting child pornography on our github

**Comment by DoctoreMad** [comment]
>child pornography

This is exactly why you're not actually part of 4chan

**Comment by Kraseo** [comment]
lol

**Comment by clusterfack** [comment]
4chan has never allowed child pornography, it has always resulted in takedowns and bans

**Comment by DoctoreMad** [comment]
There was no child pornography
What kind of distorted history did you get?

**Comment by DoctoreMad** [comment]
laraliriloliloli

**Comment by Boxe** [comment]
take intigracy too

**Comment by MrStonedOne** [comment]
We don't want him.

**Comment by DoctoreMad** [comment]
Stop glorifying trips would you

**Comment by Slignerd** [comment]
Why is Bay listed as Fallout on the actual site anyways?

**Comment by MrStonedOne** [comment]
I can't remember why i did that.

It had some sort of meme reasoning behind it.

**Comment by tortellinitony** [comment]
april fools day prank by the way

**Comment by MrStonedOne** [comment]
oh ya!

**Pull request merged**
